name: Java CI

on: 
  push:
    branches: 
      - develop
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn install -B package --file pom.xml
    - name: copy plugin.jar to testServer via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "/home/runner/work/TUMine/TUMine/target/*.jar"
        target: "/home/generalmine/server/minecraft/testServer/plugins/TUMine/newVersions"
        strip_components: 3
    - name: copy permissions.yml to testServer via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "/home/runner/work/TUMine/permissions.yml"
        target: "/home/generalmine/server/minecraft/testServer/plugins/TUMine/newVersions"
        strip_components: 0
