name: Java CI

on: 
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn install -B package --file pom.xml
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
          local: /home/runner/work/TUMine/TUMine/target/*.jar
          remote: server/minecraft/testserver/plugins/
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_USERPASSWORD }}
